#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 21 19:23:04 2021

@author: Fatima
"""

from tkinter import *
root = Tk()
root.title("Inheritance")
root.geometry("600x600")

label_name = Label(root, text="User Name : ")
label_name.place(relx=0.3,rely=0.2, anchor=CENTER)

entry_name = Entry(root)
entry_name.place(relx=0.6,rely=0.2, anchor=CENTER)

label_email = Label(root, text="Email id : ")
label_email.place(relx=0.3,rely=0.3, anchor=CENTER)

entry_email = Entry(root)
entry_email.place(relx=0.6,rely=0.3, anchor=CENTER)

label = Label(root)

dictionary = {}

class Users: 
    
    def __init__(self):
        print("This is class Users")
        
    def addUser(key, value): 
        global dictionary
        #assign value for list dictonary's key -> dictionary[key]=value
        dictionary[key]=value
        #assign the list dictionary to the label['text']
        label['text']=dictionary
        
class GetUsers(Users): 
    
    def __init__(self):
        print("This is class GetUsers")
        
    def getUser(self):
        #get value from text input "entry_name" and store it in var username
        username=entry_name.get()
        #get value from text input "entry_email" and store it in var email_id
        email_id=entry_email.get()
        #access the function addUser, pass username and email_id variable to it. 
        Users.addUser(username, email_id)
#create an object for the class GetUsers()        
l29minsleft=GetUsers()

btn = Button(root, text="Add user details", command=l29minsleft.getUser)
btn.place(relx=0.5,rely=0.4, anchor=CENTER)
label.place(relx=0.5,rely=0.5, anchor=CENTER)

root.mainloop()
