#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 28 11:57:14 2021

@author: Fatima
"""
from tkinter import *
root=Tk()
root.geometry("550x550")
moths=Label(root,text="months")
prof=Label(root,text="profits")
profmax=Label(root)
profmin=Label(root)


month = ("January", "February", "March", "April", "May", "June", "July", "August", "September",
         "October", "November", "December") 

profits = (20000,45000,78000,97000,999999999999999999999999999999999990007997677500000,456000,65000,54000,10000,30000,70000,90000)

def l():
    max_profit = max(profits)
    max_profit_index = profits.index(max_profit)
    print(max_profit_index)

    max_profit_month = month[max_profit_index]
    profmax("The maximum profit of " + str(max_profit)+ " was recorded in the month of "+ str(max_profit_month))
def g():
    min_profit = min(profits)
    min_profit_index = profits.index(min_profit)
    print(min_profit_index)

    min_profit_month = month[min_profit_index]
    profmin( "The minimum profit of "+str(min_profit)+" was recorded in the month of "+str(min_profit_month))

btn=Button(root,text="press me max",command=l)

btn.pack

profmax.pack()

btn2=Button(root,text="press me min",command=g)

profmin.pack()

btn2.pack

root.mainloop()
