#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 16 11:24:03 2021

@author: Fatima
"""
from tkinter import *
import random

root=Tk()
root.title("yusuky")
root.geometry("400x300")
wL=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]
print("sorry but i did not understant what text paramerter meant so it will be in console but you still had to press the button")
random_alpha1=1
random_alpha2=1
random_alpha3=1
random_alpha4=1
random_alpha5=1



def rl():
    raN1=random.randint(0,25)
    raN2=random.randint(0,25)
    raN3=random.randint(0,25)
    raN4=random.randint(0,25)
    raN5=random.randint(0,25)
    random_alpha1[rN1]
    random_alpha2[rN2]
    random_alpha3[rN3]
    random_alpha4[rN4]
    random_alpha5[rN5]
    rlf=wL[rn]
    print("your lucky word is : "+rlf)

    
btn=Button(root,text="gR",command=rl)
btn.pack()



root.mainloop()
